services:
  redis: 
    image: redis
    container_name: wall-app-redis
    ports:
      - '6379:6379' 
  flask:
    build: ./wall-app-be/
    container_name: wall-app-be
    environment:
      - BE_PORT=8080
      - BE_HOST=0.0.0.0
      - BE_REDIS_HOST=redis
      - BE_REDIS_PORT=6379
    ports:
      - "8080:8080"
    depends_on:
      - redis
    
  react:
    build: ./wall-app-fe
    container_name: wall-app-fe
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    ports:
      - "3000:3000"
      
