apiVersion: v1
kind: Service
metadata:
  name: wall-app-be-svc
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: wall-app-be
  ports:
  - name: tcp-port
    protocol: TCP
    port: 8080
    targetPort: 8080