apiVersion: v1
kind: Service
metadata:
  name: wall-app-fe-svc
  labels:
    app: wall-app-fe
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # type: LoadBalancer
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 3000
  selector:
    app: wall-app-fe